# Service Template with NodePort
apiVersion: v1
kind: Service
metadata:
  name: login-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: login
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007